// react-you2be/src/components/nav-bar.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";
import "../App.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUser, faVideo, faUsers } from "@fortawesome/free-solid-svg-icons";

class NavBar extends Component {
  state = {
    query: "",
  };

  bindQuery = (event) => {
    this.setState({
      query: event.target.value,
    });
  };

  search(event) {
    event.preventDefault();
  }

  renderNavButtons() {
    const user = this.props.currentUser;

    if (user != null) {
      return (
        <div className="navbar-nav ml-auto">
          <a className="nav-item nav-link active">
            <img src={user.imageSrc} className="circleSmall" />
          </a>
          <li className="nav-item dropdown">
            <a
              className="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdownMenuLink"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <b>{user.name}</b>
            </a>
            <div
              className="dropdown-menu"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <Link to={`/profile/${user.id}`} className="dropdown-item">
                <FontAwesomeIcon className="mr-1" icon={faUser} /> Profile
              </Link>
              <Link to="/my-videos" className="dropdown-item">
                <FontAwesomeIcon className="mr-1" icon={faVideo} /> My Videos
              </Link>
              <Link className="dropdown-item" to="/subscriptions">
                <FontAwesomeIcon className="mr-1" icon={faUsers} />{" "}
                Subscriptions
              </Link>
              <div className="dropdown-divider"></div>
              <Link
                to="/login"
                onClick={this.props.logout}
                className="dropdown-item"
              >
                Log out
              </Link>
            </div>
          </li>
        </div>
      );
    }

    return (
      <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div className="navbar-nav">
          <Link to="/login" className="nav-item nav-link">
            Log in
          </Link>
          <Link to="/register" className="nav-item nav-link">
            Sign up
          </Link>
        </div>
      </div>
    );
  }

  render() {
    return (
      <nav className="navbar navbar-expand-lg navbar-light react-cyan-bg">
        <span className="react-logo">
          <span className="nucleo"></span>
        </span>
        <Link to="/" className="navbar-brand ml-5">
          You2be
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        {this.renderNavButtons()}

        <form onSubmit={this.search} className="form-inline ml-5">
          <input
            onChange={this.bindQuery}
            className="form-control mr-sm-2 bg-dark text-light"
            name="query"
            type="text"
            value={this.state.query}
            placeholder="Search..."
          />
          <Link
            to={"/search/" + this.state.query}
            className="btn btn-outline-dark my-2 my-sm-0"
          >
            Search
          </Link>
        </form>
      </nav>
    );
  }
}

export default NavBar;

// youtubeTwoFront/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Observable } from 'rxjs';
import { User } from 'src/app/model/user';
import { AuthenticationService } from 'src/app/services/authentication.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

  currentUser$: Observable<any>;
  user:string = "";
  loggedIn:boolean =false;
  query:string = "";
  userId:number = 0;
  img:string = "";

  constructor(
    private authenticationService: AuthenticationService,
    private router: Router
  ) { 
    this.currentUser$=this.authenticationService.currentUser; 
  }

  ngOnInit(): void {
    this.currentUser$.subscribe(res => {
      var userValue:User = this.authenticationService.currentUserValue;
      if(userValue!=null && userValue!=undefined){
        this.user = userValue.name;
        this.userId = userValue.id;
        this.img = userValue.imageSrc;
        console.log(userValue);
        
        this.loggedIn=true;
      }else{
        this.user = "";
        this.loggedIn=false;
      }
    });
  }

  logout() {
    this.authenticationService.logout();
  }

}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" routerLink="">You2be</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!--LOGGED OUT-->
    <div *ngIf="!loggedIn" class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" routerLink="/login">Log in</a>
        <a class="nav-item nav-link" routerLink="/register">Sign up</a>
      </div>
    </div>
    
    <!--LOGGED IN-->
    <div *ngIf="loggedIn" class="navbar-nav ml-auto">
        <a class="nav-item nav-link active"><img src="{{img}}" class="circleSmall"></a>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b>{{user}}</b></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" routerLink="/profile/{{userId}}"><i class="fa fa-user" aria-hidden="true"></i> Profile</a>
                <a class="dropdown-item" routerLink="/myvideos"><i class="fa fa-video-camera" aria-hidden="true"></i> My Videos</a>
                <a class="dropdown-item" routerLink="/subscriptions"><i class="fa fa-users" aria-hidden="true"></i> Subscriptions</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" (click)=logout() routerLink="/login">Log out</a>
            </div>
        </li>
    </div>
 
    <!--SEARCH-->
    <form class="form-inline ml-5">
        <input class="form-control mr-sm-2" name="searchQueryImput" type="search" [(ngModel)]="query" placeholder="Search..." aria-label="Search">
        <button class="btn btn-outline-light my-2 my-sm-0" routerLink="/results/{{query}}" type="submit">Search</button>
    </form>
  </nav>
