// react-you2be/src/components/subscriptions.jsx
import React, { Component } from "react";
import SubService from "../services/sub-service";
import ProfileCard from "./profile-card";

class Subscriptions extends Component {
  state = {
    channelSubs: [],
    mySubscriptions: [],
  };

  componentDidMount() {
    this.fetch();
  }

  fetch = () => {
    SubService.getSubscriptions()
      .then((res) => {
        this.setState({
          channelSubs: res.data.channelSubs,
          mySubscriptions: res.data.mySubscriptions,
        });
      })
      .catch((err) => {
        console.log(err);
      });
  };

  render() {
    var channelSubs = this.state.channelSubs;
    var mySubscriptions = this.state.mySubscriptions;

    return (
      <React.Fragment>
        <ul className="nav nav-tabs mt-5" id="myTab" role="tablist">
          <li className="nav-item">
            <a
              className="nav-link active react-cyan"
              id="mySubscriptions-tab"
              data-toggle="tab"
              href="#mySubscriptions"
              role="tab"
              aria-controls="mySubscriptions"
              aria-selected="true"
            >
              My subscriptions
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link react-cyan"
              id="channelSubs-tab"
              data-toggle="tab"
              href="#channelSubs"
              role="tab"
              aria-controls="channelSubs"
              aria-selected="false"
            >
              Channel subscribers
            </a>
          </li>
        </ul>
        <div className="tab-content" id="myTabContent">
          <div
            className="tab-pane fade show active"
            id="mySubscriptions"
            role="tabpanel"
            aria-labelledby="mySubscriptions-tab"
          >
            <div className="container mt-5">
              {mySubscriptions.map((profile) => (
                <div key={profile.id} className="row">
                  <div className="col">
                    <ProfileCard profile={profile} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div
            className="tab-pane fade"
            id="channelSubs"
            role="tabpanel"
            aria-labelledby="channelSubs-tab"
          >
            <div className="container mt-5">
              <div className="container mt-5">
                {channelSubs.map((profile) => (
                  <div key={profile.id} className="row">
                    <div className="col">
                      <ProfileCard profile={profile} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </React.Fragment>
    );
  }
}

export default Subscriptions;

// youtubeTwoFront/src/app/components/subscriptions/subscriptions.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { AuthenticationService } from 'src/app/services/authentication.service';
import { SubService } from 'src/app/services/sub.service';

@Component({
  selector: 'app-subscriptions',
  templateUrl: './subscriptions.component.html',
  styleUrls: ['./subscriptions.component.scss']
})
export class SubscriptionsComponent implements OnInit {

  mySubscriptions=[];
  channelSubs=[];
  currentUser$: Observable<any>;
  userValue=null;

  constructor(private subService:SubService,private authenticationService: AuthenticationService) {
    this.currentUser$=this.authenticationService.currentUser; 
  }

  ngOnInit(): void {
    this.currentUser$.subscribe(res => {
      this.userValue = this.authenticationService.currentUserValue;

      if(this.userValue!=null && this.userValue!=undefined){              
        this.getSubs();
      }
    });
  }

  getSubs(){
    this.subService.getSubscriptions().subscribe(
      res => {
        console.log(res);
        
        this.mySubscriptions = res.mySubscriptions;
        this.channelSubs = res.channelSubs;
      },
      err => { 
        console.log(err);
      }
    )
  }

  subscribe(channel){
    this.subService.subscribe(channel.id).subscribe(
      res => {
        channel.alreadySubscribed=true;
        channel.numOfSubs = channel.numOfSubs + 1;
        this.mySubscriptions.push(channel);
      },
      err => { 
        console.log(err);
      }
    )
  }

  unsubscribe(channel){
    this.subService.unsubscribe(channel.id).subscribe(
      res => {
        channel.alreadySubscribed=false;
        channel.numOfSubs = channel.numOfSubs - 1;

        for(let i=0;i<this.mySubscriptions.length;i++){
          if(this.mySubscriptions[i].id == channel.id){
            this.mySubscriptions.splice(i,1);
            break;
          }
        }
      },
      err => { 
        console.log(err);
      }
    )
  }

}

<div class="container mt-5">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="mySubscriptions-tab" data-toggle="tab" href="#mySubscriptions" role="tab" aria-controls="mySubscriptions" aria-selected="true">My subscriptions</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="channelSubs-tab" data-toggle="tab" href="#channelSubs" role="tab" aria-controls="channelSubs" aria-selected="false">Channel subscribers</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="mySubscriptions" role="tabpanel" aria-labelledby="mySubscriptions-tab">
            <div class="container mt-5">
                <div class="row" *ngFor="let channel of mySubscriptions">
                    <div class="col-3"></div>
                    <div class="col-6 border-top">
                        <div class="row mt-3 mb-3">
                            <div class="col-2">
                                <img src="{{channel.userImage}}" class="circleLarge" routerLink="/profile/{{channel.id}}">
                            </div>
                            <div class="col-7">                            
                                <div class="row">
                                    <label routerLink="/profile/{{channel.id}}"><b>{{channel.username}}</b></label>
                                  </div>
                                  <div class="row">
                                    <label class="text-muted">{{channel.numOfSubs}} subscribers</label>
                                  </div>
                            </div>
                            <div class="col-2 mt-3">
                                
                                <button *ngIf="channel.alreadySubscribed==true" (click)="unsubscribe(channel)" class="btn btn-outline-primary">UNSUBSCRIBE</button>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-3"></div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="channelSubs" role="tabpanel" aria-labelledby="channelSubs-tab">
            <div class="container mt-5">
                <div class="row" *ngFor="let channel of channelSubs">
                    <div class="col-3"></div>
                    <div class="col-6 border-top">
                        <div class="row mt-3 mb-3">
                            <div class="col-2">
                                <img src="{{channel.userImage}}" class="circleLarge" routerLink="/profile/{{channel.id}}">
                            </div>
                            <div class="col-7">                            
                                <div class="row">
                                    <label routerLink="/profile/{{channel.id}}"><b>{{channel.username}}</b></label>
                                  </div>
                                  <div class="row">
                                    <label class="text-muted">{{channel.numOfSubs}} subscribers</label>
                                  </div>
                            </div>
                            <div class="col-2 mt-3">
                                <ng-container *ngIf="userValue!=null && userValue.id!=channel.id">
                                    <button *ngIf="channel.alreadySubscribed==false" (click)="subscribe(channel)" class="btn btn-primary">SUBSCRIBE</button>
                                    <button *ngIf="channel.alreadySubscribed==true" (click)="unsubscribe(channel)" class="btn btn-outline-primary">UNSUBSCRIBE</button>
                                </ng-container>
                            </div>
                        </div>
                    </div>
                    <div class="col-3"></div>
                </div>
            </div>
        </div>
    </div>
</div>
