// react-you2be/src/components/search-results.jsx
import React, { Component } from "react";
import VideoCard from "./video-card";
import ProfileCard from "./profile-card";
import SearchService from "../services/search-service";

class SearchResults extends Component {
  state = {
    videos: [],
    profiles: [],
  };

  componentDidMount() {
    this.search();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.match.params.query !== this.props.match.params.query) {
      this.search();
    }
  }

  search = () => {
    const query = this.props.match.params.query;

    SearchService.searchVideosAndChannels(query)
      .then((res) => {
        const videos = res.data.videos;
        const profiles = res.data.channels;

        this.setState({
          videos: videos,
          profiles: profiles,
        });
      })
      .catch((err) => {
        console.log(err);
      });
  };

  render() {
    return (
      <React.Fragment>
        <ul className="nav nav-tabs mt-5" id="myTab" role="tablist">
          <li className="nav-item">
            <a
              className="nav-link active react-cyan"
              id="videos-tab"
              data-toggle="tab"
              href="#videos"
              role="tab"
              aria-controls="videos"
              aria-selected="true"
            >
              Videos
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link react-cyan"
              id="channels-tab"
              data-toggle="tab"
              href="#channels"
              role="tab"
              aria-controls="channels"
              aria-selected="false"
            >
              Channels
            </a>
          </li>
        </ul>
        <div className="tab-content" id="myTabContent">
          <div
            className="tab-pane fade show active"
            id="videos"
            role="tabpanel"
            aria-labelledby="videos-tab"
          >
            <div className="container mt-5">
              <div className="row">
                {this.state.videos.map((video) => (
                  <div key={video.id} className="col-4 mt-5">
                    <VideoCard video={video} />
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div
            className="tab-pane fade"
            id="channels"
            role="tabpanel"
            aria-labelledby="channels-tab"
          >
            <div className="container mt-5">
              {this.state.profiles.map((profile) => (
                <ProfileCard
                  user={this.props.user}
                  key={profile.id}
                  profile={profile}
                />
              ))}
            </div>
          </div>
        </div>
      </React.Fragment>
    );
  }
}

export default SearchResults;

// youtubeTwoFront/src/app/components/search-results/search-results.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { User } from 'src/app/model/user';
import { AuthenticationService } from 'src/app/services/authentication.service';
import { SearchService } from 'src/app/services/search.service';
import { SubService } from 'src/app/services/sub.service';

@Component({
  selector: 'app-search-results',
  templateUrl: './search-results.component.html',
  styleUrls: ['./search-results.component.scss']
})
export class SearchResultsComponent implements OnInit {

  videos=[];
  channels=[];
  currentUser$: Observable<any>;
  userValue = null;

  constructor(private searchService:SearchService, private activatedRoute: ActivatedRoute,private authenticationService: AuthenticationService,private subService:SubService) {
    this.currentUser$=this.authenticationService.currentUser; 
   }

  ngOnInit(): void {
    
    this.userValue = this.authenticationService.currentUserValue;   

    this.activatedRoute.params.subscribe(routeParams => {
      this.search(this.activatedRoute.snapshot.paramMap.get('query'));
    });
  }

  search(query){
    this.searchService.searchVideosAndChannels(query).subscribe(
      res => {
        console.log(res);
        this.videos = res.videos;
        this.channels = res.channels;
        if(this.userValue!=null){
          this.checkIfAlreadySubscribed(this.channels);
        }
      },
      err => { 
        console.log(err);
      }
    )
  }

  checkIfAlreadySubscribed(user){
    this.subService.checkIfAlreadySubscribedGroup(user).subscribe(
      res => {
        this.channels = res;
      },
      err => { 
        console.log(err);
      }
    )
  }

  subscribe(channel){
    this.subService.subscribe(channel.id).subscribe(
      res => {
        channel.alreadySubscribed=true;
        channel.numOfSubs = channel.numOfSubs + 1;
      },
      err => { 
        console.log(err);
      }
    )
  }

  unsubscribe(channel){
    this.subService.unsubscribe(channel.id).subscribe(
      res => {
        channel.alreadySubscribed=false;
        channel.numOfSubs = channel.numOfSubs - 1;
      },
      err => { 
        console.log(err);
      }
    )
  }
}

<div class="container mt-5">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="videos-tab" data-toggle="tab" href="#videos" role="tab" aria-controls="videos" aria-selected="true">Videos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="channels-tab" data-toggle="tab" href="#channels" role="tab" aria-controls="channels" aria-selected="false">Channels</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="videos" role="tabpanel" aria-labelledby="videos-tab">
            <div class="container mt-5">
                <div class="row">
                    <div class="col mb-5" *ngFor="let video of videos">
                        <div class="card" routerLink="/video/{{video.id}}" style="width: 20rem; height: 25rem;">
                            <img class="card-img-top" src="assets/img/videoImage.jpg" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">{{video.title}}</h5>
                                <p class="card-text">{{video.description}}</p>
                            </div>
                            <div class="card-footer text-muted">
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-eye" aria-hidden="true"></i> {{video.views}}
                                    </div>
                                    <div class="col">
                                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> {{video.likes}}
                                    </div>
                                    <div class="col">
                                        <i class="fa fa-thumbs-down" aria-hidden="true"></i> {{video.dislikes}}
                                    </div>
                                    <div class="col">
                                        <i class="fa fa-comment" aria-hidden="true"></i> {{video.numOfComments}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="channels" role="tabpanel" aria-labelledby="channels-tab">
            <div class="container mt-5">
                <div class="row" *ngFor="let channel of channels">
                    <div class="col-3"></div>
                    <div class="col-6 border-top">
                        <div class="row mt-3 mb-3">
                            <div class="col-2">
                                <img src="{{channel.userImage}}" class="circleLarge" routerLink="/profile/{{channel.id}}">
                            </div>
                            <div class="col-7">                            
                                <div class="row">
                                    <label routerLink="/profile/{{channel.id}}"><b>{{channel.username}}</b></label>
                                  </div>
                                  <div class="row">
                                    <label class="text-muted">{{channel.numOfSubs}} subscribers</label>
                                  </div>
                            </div>
                            <div class="col-2 mt-3">
                                <ng-container *ngIf="userValue!=null && userValue.id!=channel.id">
                                    <button *ngIf="channel.alreadySubscribed==false" (click)="subscribe(channel)" class="btn btn-primary">SUBSCRIBE</button>
                                    <button *ngIf="channel.alreadySubscribed==true" (click)="unsubscribe(channel)" class="btn btn-outline-primary">UNSUBSCRIBE</button>
                                </ng-container>
                            </div>
                        </div>
                    </div>
                    <div class="col-3"></div>
                </div>
            </div>
        </div>
    </div>
</div>
