// youtubeTwoFront/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LoginUser } from 'src/app/model/login-user';
import { first } from 'rxjs/operators';
import { AuthenticationService } from 'src/app/services/authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  user:LoginUser = new LoginUser();

  constructor(private authService:AuthenticationService, private router: Router) { }

  ngOnInit(): void {
  }

  public submitLogin(){
    console.log(this.user);

    if(this.user.username!=null || this.user.password!=null)

    this.authService.login(this.user.username, this.user.password)
      .pipe(first())
      .subscribe(
          data => {
            this.router.navigate(['']);
          },
          error => {
            console.log(error);
        });

  }

}

<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h2>Login</h2>
            <form>
                <div class="form-group">
                    <label for="usernameInput">Username</label>
                    <input input name="username" [(ngModel)]="user.username" type="text" class="form-control" id="usernameInput" placeholder="Enter username">
                </div>
                <div class="form-group">
                  <label for="passwordInput">Password</label>
                  <input input name="password" [(ngModel)]="user.password" type="password" class="form-control" id="passwordInput" placeholder="Enter password">
                </div>
                <button name="submit" type="submit" (click)="submitLogin()" class="btn btn-primary">Log in</button>
            </form>
        </div>
    </div>
</div>

// react-you2be/src/components/login.jsx
import React, { Component } from "react";
import "../App.css";
import AuthService from "../services/auth";

class Login extends Component {
  state = {
    username: "",
    password: "",
  };

  constructor() {
    super();

    this.handleSubmit = this.handleSubmit.bind(this);
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(event) {
    const name = event.target.name;

    this.setState({
      [name]: event.target.value,
    });
  }

  handleSubmit(event) {
    event.preventDefault();

    AuthService.login(this.state.username, this.state.password)
      .then((res) => {
        this.props.login();
        this.props.history.push("/");
      })
      .catch((err) => {
        console.log(err);
      });
  }

  render() {
    return (
      <div className="row mt-5 text-light">
        <div className="col"></div>
        <div className="col">
          <h2>Login</h2>
          <form onSubmit={this.handleSubmit}>
            <div className="form-group">
              <label htmlFor="usernameInput">Username</label>
              <input
                value={this.state.username}
                name="username"
                type="text"
                className="form-control"
                id="usernameInput"
                placeholder="Enter username"
                onChange={this.handleChange}
              />
            </div>
            <div className="form-group">
              <label htmlFor="passwordInput">Password</label>
              <input
                value={this.state.password}
                name="password"
                type="password"
                className="form-control"
                id="passwordInput"
                placeholder="Enter password"
                onChange={this.handleChange}
              />
            </div>
            <button name="submit" type="submit" className="react-cyan-bg btn">
              Log in
            </button>
          </form>
        </div>
        <div className="col"></div>
      </div>
    );
  }
}

export default Login;
