// react-you2be/src/components/comment.jsx
import React, { Component } from "react";
import CommentService from "../services/comment-service";
import CommentInput from "./comment-input";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTrash } from "@fortawesome/free-solid-svg-icons";
import { Link } from "react-router-dom";

class Comment extends Component {
  state = {
    replies: [],
  };

  componentDidMount() {
    CommentService.getReplies(this.props.comment.id)
      .then((res) => {
        this.setState({
          replies: res.data,
        });
      })
      .catch((err) => {
        console.log(err);
      });
  }

  renderCommentInput = () => {
    if (this.props.user == null) {
      return null;
    }

    return (
      <CommentInput
        parentId={this.props.comment.id}
        user={this.props.user}
        videoId={this.props.comment.videoId}
        onCommentAdd={this.handleReplyAdd}
      />
    );
  };

  handleReplyAdd = (reply) => {
    var replies = this.state.replies;
    replies.push(reply);

    this.setState({
      replies: replies,
    });
  };

  deleteComment = () => {
    const commentId = this.props.comment.id;

    CommentService.deleteComment(commentId)
      .then((res) => {
        this.props.onCommentDelete(commentId);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  handleReplyDelete = (replyId) => {
    const replies = this.state.replies.filter((r) => r.id !== replyId);

    this.setState({
      replies: replies,
    });
  };

  renderDeleteButton = () => {
    if (
      this.props.user != null &&
      (this.props.user.id === this.props.comment.userId ||
        this.props.user.id === this.props.comment.videoUploaderId)
    ) {
      return (
        <button className="btn btn-outline-light" onClick={this.deleteComment}>
          <FontAwesomeIcon icon={faTrash} />
        </button>
      );
    } else {
      return null;
    }
  };

  render() {
    return (
      <div id={"accordion" + this.props.comment.id} className="mt-3">
        <div className="card bg-dark text-light">
          <div className="card-header" id="headingOne">
            <div className="row ml-2">
              <div className="col-0 mt-2">
                <Link to={`/profile/${this.props.comment.userId}`}>
                  <img
                    src={this.props.comment.userImage}
                    className="circleMedium"
                    alt="User"
                  />
                </Link>
              </div>
              <div className="col">
                <div className="row">
                  <div className="col-8">
                    <Link to={`/profile/${this.props.comment.userId}`}>
                      <label className="text-light">
                        <b>{this.props.comment.username}</b>
                      </label>
                    </Link>
                  </div>
                  <div className="col">
                    <label className="text-muted small-text">
                      {this.props.comment.createdAt}
                    </label>
                  </div>
                </div>
                <div className="row">
                  <div className="col-11">
                    <p>{this.props.comment.text}</p>
                  </div>
                  <div className="col-1">{this.renderDeleteButton()}</div>
                </div>
              </div>
            </div>

            <h6 className="mb-0">
              <a
                className="btn btn-link react-cyan"
                data-toggle="collapse"
                href={"#collapseOne" + this.props.comment.id}
                aria-expanded="false"
                aria-controls={"collapseOne" + this.props.comment.id}
              >
                View All Replies
              </a>
            </h6>
          </div>

          <div
            id={"collapseOne" + this.props.comment.id}
            className="collapse"
            aria-labelledby={"headingOne" + this.props.comment.id}
          >
            <div className="card-body">
              <div className="row mt-3">
                <div className="col">
                  {this.state.replies.map((reply) => {
                    return (
                      <Comment
                        key={reply.id}
                        user={this.props.user}
                        comment={reply}
                        onCommentDelete={this.handleReplyDelete}
                      />
                    );
                  })}
                </div>
              </div>
              <div className="mt-3">{this.renderCommentInput()}</div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Comment;

// youtubeTwoFront/src/app/components/comment/comment.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { CommentService } from 'src/app/services/comment.service';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.scss']
})
export class CommentComponent implements OnInit {

  @Input() comment;
  @Input() userValue;
  @Output() deleteCommentEmmiter: EventEmitter<any> = new EventEmitter<any>();

  replies=[];
  shouldGetData=true;
  newCommentText="";

  constructor(private commentService:CommentService) { }

  ngOnInit(): void {
  }

  getChildren(){

    if(this.shouldGetData==false){
      return;
    }

    this.shouldGetData = false;

    this.commentService.getReplies(this.comment.id).subscribe(
      res => {
        this.replies = res
      },
      err => { 
        console.log(err);
      }
    )
  }

  addComment(){
    var newComment = {
      "text":this.newCommentText,
      "videoId":this.comment.videoId,
      "parentId":this.comment.id
    }

    this.commentService.addComment(newComment).subscribe(
      res => {
        this.replies.push(res);
        this.comment.numOfReplies = this.comment.numOfReplies + 1;
        this.newCommentText="";
      },
      err => { 
        console.log(err);
      }
    )
  }
  

  handleDeleteCommentEvent(deletedComment){
    
    for(let i =0;i<this.replies.length;i++){
      if(this.replies[i].id == deletedComment.id) {
        this.replies.splice(i, 1);
        break;
      }
    }
  }

  deleteComment(){

    this.commentService.deleteComment(this.comment.id).subscribe(
      res => {
        this.deleteCommentEmmiter.emit(this.comment);
      },
      err => { 
        console.log(err);
      }
    )
  }
}

<div id="accordion{{comment.id}}">
    <div class="card">
      <div class="card-header" id="headingOne">

        <div class="row ml-2">
            <div class="col-0 mt-2">
              <img src="{{comment.userImage}}" class="circleMedium">
            </div>
            <div class="col">
              <div class="row">
                <div class="col-8">
                    <label routerLink="/profile/{{comment.userId}}"><b>{{comment.username}}</b></label>
                </div>
                <div class="col-4">
                    <label class="text-muted small-text">{{comment.createdAt}}</label>
                    <button *ngIf="userValue!=null && (userValue.id==comment.userId || userValue.id==comment.videoUploaderId)" (click)="deleteComment()" class="btn btn-outline-dark ml-5"><i class="fa fa-trash" aria-hidden="true"></i></button>
                </div>
              </div>
              <div class="row">
                <div class="col">
                    <p>{{comment.text}}</p>
                </div>
              </div>
            </div>  
        </div>

        <h6 class="mb-0">
          <a class="btn btn-link" data-toggle="collapse" (click)="getChildren()" href="#collapseOne{{comment.id}}" aria-expanded="false" [attr.aria-controls]="'collapseOne'+comment.id">
            View All Replies
          </a>
        </h6>
      </div>
  
      <div id="collapseOne{{comment.id}}" class="collapse" [attr.aria-labelledby]="'headingOne'+comment.id">
        <div class="card-body">
            <div class="row mt-3" *ngFor="let reply of replies">
                <div class="col">
                    <app-comment [comment]="reply" [userValue]="userValue" (incrementCommentNumber)="emitCommentIncrementEvent()" (decrementCommentNumber)="emitCommentDecrementEvent($event)" (deleteCommentEmmiter)="handleDeleteCommentEvent($event)"></app-comment>
                </div>
            </div>
            <div class="row mt-3" *ngIf="userValue!=null">
                <div class="col-0 ml-3 text-center">
                  <label><img src="{{userValue.imageSrc}}" class="circleMedium"></label>
                </div>
                <div class="col-10">
                  <textarea type="text" class="form-control" [(ngModel)]="newCommentText" id="commentInput" placeholder="Add a public comment..."></textarea>
                </div>
                <div class="col-1">
                  <button (click)="addComment()" class="btn btn-primary">Reply</button>
                </div>
              </div>
        </div>
      </div>
    </div>
</div>
